version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test-api:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
              command: cd api
            - run: npm install
            - run: npm test
workflows:
    api:
      jobs:
        - build-and-test-api
